import { ClerkProvider } from '@clerk/nextjs/app-beta';
import '../../globals.css';
import React from 'react';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface SignInLayoutProps {
  children: React.ReactNode;
}

export default function SignUpLayout({ children }: SignInLayoutProps) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${inter.className} h-full bg-white`}>
        <body className="h-full">{children}</body>
      </html>
    </ClerkProvider>
  );
}
