import './globals.css';
import React from 'react';
import { ClerkProvider } from '@clerk/nextjs/app-beta';
import AppShell from './components/appShell/AppShell';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full bg-gray-100">
        <body className="h-full">
          <AppShell>{children}</AppShell>
        </body>
      </html>
    </ClerkProvider>
  );
}
