import { ClerkProvider } from '@clerk/nextjs/app-beta';
import '../../globals.css';
import React from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface SignUpLayoutProps {
  children: React.ReactNode;
}

export default function SignUpLayout({ children }: SignUpLayoutProps) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full bg-gray-50">
        <body className="h-full">{children}</body>
      </html>
    </ClerkProvider>
  );
}
